{% set name = "sunpy-soar" %}
{% set version = "1.11.1" %}
{% set sha256 = "742ce16127c0b0ee80825e0a02790816299e096b332ea32c25a91e0f5677ed13" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - astropy >=5.3
    - sunpy >=6.0
    - requests >=2.28

test:
  imports:
    - sunpy_soar
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/sunpy/sunpy-soar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A sunpy plugin for accessing data in the Solar Orbiter Archive (SOAR). '
  description: |
    sunpy-soar is a sunpy plugin for accessing data in the Solar Orbiter Archive (SOAR) via.
    the sunpy.net.Fido search interface.
  doc_url: https://docs.sunpy.org/projects/soar/
  dev_url: https://github.com/sunpy/sunpy-soar

extra:
  recipe-maintainers:
    - cadair
    - hayesla
    - wtbarnes
