{% set name = "sunpy-soar" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1aa78c7cfffdcebb2ce4e29101234af88001659a8ba5191018bd9d37d8aee28e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - sunpy >=2.1

test:
  imports:
    - sunpy_soar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dstansby/sunpy-soar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A sunpy plugin for accessing data in the Solar Orbiter Archive (SOAR). '
  description: |
    sunpy-soar is a sunpy plugin for accessing data in the Solar Orbiter Archive (SOAR) via.
    the sunpy.net.Fido search interface.
  doc_url: https://github.com/dstansby/sunpy-soar/blob/main/README.rst
  dev_url: https://github.com/dstansby/sunpy-soar

extra:
  recipe-maintainers:
    - dstansby
